# hosts/hephaestus/default.nix
#
# Hephaestus — OCI ARM free tier (aarch64)
# Role: game servers — Minecraft via Pelican Panel
#
# Resources: 3 OCPU / 18 GB RAM / 150 GB storage
#
# Pelican Wings manages game server containers via Docker.
# The Panel (web UI) runs in Docker Compose and is accessible via Traefik on
# Panoptes (Tailscale-only — never exposed to the public internet).
#
# Pelican is the actively maintained fork of Pterodactyl (Pterodactyl is
# unmaintained as of 2024). Panel image: ghcr.io/pelican-dev/panel
#
# Minecraft ports are open to the public internet (players need to connect).
# All admin access goes through Tailscale.
#
# INTENTIONALLY ISOLATED from Tartarus — game servers have no path to
# the backup storage. Log4j and similar vulnerabilities in game servers
# cannot pivot to the off-site backup.
#
# On first boot:
#   sudo tailscale up --auth-key=<key>
#
# Then deploy the Pelican stack:
#   sudo systemctl start pterodactyl
#
# Wings first-run (after Panel is up):
#   1. Log into the Panel at https://panel.0x21.uk
#   2. Add a new Node pointing to this host
#   3. Copy the generated config.yml from the Panel
#   4. Place it at /etc/pterodactyl/config.yml on this host
#   5. systemctl start pterodactyl-wings
#   See: https://pelican.dev/docs/wings/install

{ config, pkgs, lib, net, ... }:

{
  imports = [
    ./hardware-configuration.nix
    ./services/stacks.nix
  ];

  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # ---------------------------------------------------------------------------
  # Identity
  # ---------------------------------------------------------------------------
  networking.hostName = "hephaestus";
  networking.useDHCP  = true;

  # Off-site — use public DNS, not the home network's AdGuard
  networking.nameservers = [ "1.1.1.1" "1.0.0.1" ];

  # ---------------------------------------------------------------------------
  # System packages
  # ---------------------------------------------------------------------------
  environment.systemPackages = with pkgs; [
    curl wget htop git docker-compose
  ];

  security.sudo.wheelNeedsPassword = false;

  users.users.tommy = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    shell = pkgs.bash;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN+wnifYivhxDUTvfGcd1ao2s39uKwDc8C3HEG0M7noS"
    ];
  };

  # ---------------------------------------------------------------------------
  # Docker — required for Pterodactyl Wings game server containers
  # ---------------------------------------------------------------------------
  virtualisation.docker = {
    enable           = true;
    autoPrune.enable = true;
    storageDriver    = "overlay2";
  };

  # ---------------------------------------------------------------------------
  # Pterodactyl Wings — game server daemon
  #
  # Wings manages Docker containers for each game server. It needs to run as
  # root to create and manage those containers.
  #
  # Wings binary is downloaded on first start (ARM64 build from GitHub releases).
  # Config at /etc/pterodactyl/config.yml — generated by the Panel on node setup.
  #
  # Required directories:
  #   /etc/pterodactyl/    — Wings config
  #   /var/lib/pterodactyl/volumes/  — game server data
  #   /tmp/pterodactyl/    — temporary files
  # ---------------------------------------------------------------------------
  systemd.tmpfiles.rules = [
    "d /etc/pterodactyl               0750 root root -"
    "d /var/lib/pterodactyl           0750 root root -"
    "d /var/lib/pterodactyl/volumes   0750 root root -"
    "d /tmp/pterodactyl               0755 root root -"
  ];

  systemd.services.pterodactyl-wings = {
    description   = "Pelican Wings — game server daemon";
    documentation = [ "https://pelican.dev/docs/wings/install" ];

    after    = [ "docker.service" "network-online.target" ];
    requires = [ "docker.service" ];
    wants    = [ "network-online.target" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig = {
      WorkingDirectory = "/etc/pterodactyl";
      # Download the Pelican Wings binary on first run (ARM64 for OCI Ampere A1)
      # Pelican is the actively maintained fork of Pterodactyl Wings.
      ExecStartPre = pkgs.writeShellScript "wings-install" ''
        if [ ! -f /usr/local/bin/wings ]; then
          echo "[wings] Downloading Pelican Wings (aarch64)..."
          ${pkgs.curl}/bin/curl -Lo /usr/local/bin/wings \
            "https://github.com/pelican-dev/wings/releases/latest/download/wings_linux_arm64"
          chmod +x /usr/local/bin/wings
          echo "[wings] Wings installed."
        fi
        if [ ! -f /etc/pterodactyl/config.yml ]; then
          echo "[wings] WARNING: /etc/pterodactyl/config.yml not found."
          echo "[wings] Generate it from the Pelican Panel → Nodes → Configuration."
          exit 1
        fi
      '';
      ExecStart  = "/usr/local/bin/wings --config /etc/pterodactyl/config.yml";
      Restart    = "on-failure";
      RestartSec = "10s";
      # Wings requires root to create and manage Docker containers
      User  = "root";
      Group = "root";
    };
  };

  # ---------------------------------------------------------------------------
  # Prometheus node exporter — scraped by Panoptes over Tailscale
  # ---------------------------------------------------------------------------
  services.prometheus.exporters.node = {
    enable            = true;
    port              = 9100;
    enabledCollectors = [ "systemd" "processes" "filesystem" ];
    listenAddress     = "0.0.0.0";
  };

  # ---------------------------------------------------------------------------
  # Firewall
  #
  # Minecraft ports (25565–25574): open to the public internet.
  #   Allocate one port per server (Wings assigns each server a unique port).
  #   25565 is the Minecraft default; 25566–25574 covers up to 10 servers.
  #   Adjust the range if you run more or fewer servers.
  #
  # Wings SFTP (2022): open to the public internet so players and admins can
  #   use the Pterodactyl file manager's SFTP access.
  #
  # Admin ports (Panel, node exporter): Tailscale-only.
  #   The Panel is proxied by Traefik on Panoptes — players never hit it directly.
  #
  # Wings API (8080): Tailscale-only.
  #   The Panel calls Wings over Tailscale. Wings should not be reachable
  #   from the public internet.
  # ---------------------------------------------------------------------------
  networking.firewall = {
    # Public internet — game server ports only
    allowedTCPPorts = [
      22              # SSH (key-auth only, from ssh-hardening.nix)
      2022            # Pterodactyl Wings SFTP (file manager access)
      25565           # Minecraft default port
      25566 25567 25568 25569 25570   # Additional game server ports
      25571 25572 25573 25574         # Reserve more for future servers
    ];
    allowedUDPPorts = [
      25565 25566 25567 25568 25569   # Minecraft UDP (Bedrock edition, if used)
      25570 25571 25572 25573 25574
    ];

    # Tailscale-only — admin + Panel + Wings API
    interfaces.tailscale0.allowedTCPPorts = [
      8080   # Pterodactyl Panel (proxied by Traefik on Panoptes)
      8443   # Pterodactyl Wings API (Panel → Wings communication)
      9100   # Prometheus node exporter
    ];
  };

  # ---------------------------------------------------------------------------
  # NixOS state version
  # ---------------------------------------------------------------------------
  system.stateVersion = "25.11";
}
