# hosts/hephaestus/hardware-configuration.nix
# Generated by nixos-generate-config on Hephaestus (OCI ARM aarch64).
# Do not modify this file manually.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "virtio_scsi" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # OCI ARM uses GRUB with efiInstallAsRemovable (installs as BOOTAA64.EFI).
  # Matches the bootstrap oci-image.nix bootloader setup.
  # canTouchEfiVariables must be false — OCI does not support EFI variable writes.
  boot.loader.grub = {
    enable                = true;
    device                = "nodev";
    efiSupport            = true;
    efiInstallAsRemovable = true;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f222513b-ded1-49fa-b591-20ce86a2fe7f";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
